/**
 * <p>Title: CallableStatement的监控类接</p>
 * <p>Description: 资源监控层</p>
 * <p>Copyright: Copyright (c) 2006</p>
 * <p>Company: 北京易初电子技术有限公司</p>
 * @author 黄瑞文
 * @version 1.0
 * 2006-11-22
 */

package com.irdstudio.smcenter.core.assembly.imdbcp.resource;

import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import com.irdstudio.smcenter.core.assembly.imdbcp.encode.CustomCallableStatement;
import com.irdstudio.smcenter.core.assembly.imdbcp.encode.Util;

/**
 * 资源监控层，CallableStatement的监控类
 * @author hrw
 */
public class RsCallableStatement extends CustomCallableStatement implements RsInterface {
	
	/** 最后执行SQL */
	private String lastSql = null;
	/** 最后执行SQL时间 */
	private long lastSqlTime = 0;
	/** 连接 */
	private RsConnection conn = null;
   
	public RsCallableStatement(CallableStatement _cs, String charSet, int encodeType) {
		super(_cs, charSet, encodeType);
	}
	
	public ResultSet executeQuery() throws SQLException {
		ResultSet _rs = cs.executeQuery();
		RsResultSet rs = new RsResultSet(_rs,this.charSet,this.encodeType);
		conn.addResource(rs);
		rs.setLastSql(lastSql);
		
		return rs;
	}
	
	public ResultSet executeQuery(String sql) throws SQLException {
		this.setLastSql(sql);
		String enCodeSql = Util.encodeString(sql, this.charSet, this.encodeType);
		ResultSet _rs = cs.executeQuery(enCodeSql);
		RsResultSet rs = new RsResultSet(_rs,this.charSet,this.encodeType);
		conn.addResource(rs);
		rs.setLastSql(lastSql);
		
		return rs;
	}
	
	public int executeUpdate(String sql) throws SQLException {
		this.setLastSql(sql);

		return super.executeUpdate(sql);
	}
	
	public void close() throws SQLException {
		conn.removeResource(this);
		super.close();
	}
	
	public boolean execute(String sql) throws SQLException {
		this.setLastSql(sql);

		return super.execute(sql);
	}
	
	public ResultSet getResultSet() throws SQLException {
		ResultSet _rs = cs.getResultSet();
		RsResultSet rs = new RsResultSet(_rs,this.charSet,this.encodeType);
		conn.addResource(rs);
		rs.setLastSql(lastSql);
		
		return rs;
	}
	
	public void addBatch(String sql) throws SQLException {
		this.setLastSql(sql);

		super.addBatch(sql);
	}
	
	public ResultSet getGeneratedKeys() throws SQLException {
		ResultSet _rs = cs.getGeneratedKeys();
		RsResultSet rs = new RsResultSet(_rs,this.charSet,this.encodeType);
		conn.addResource(rs);
		rs.setLastSql(lastSql);
		
		return rs;
	}
	
	public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		this.setLastSql(sql);

		return super.executeUpdate(sql, autoGeneratedKeys);
	}
	
	public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
		this.setLastSql(sql);
		
		return super.executeUpdate(sql, columnIndexes);
	}
	
	public int executeUpdate(String sql, String[] columnNames) throws SQLException {
		this.setLastSql(sql);
		
		return super.executeUpdate(sql, columnNames);
	}
	
	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
		this.setLastSql(sql);
		
		return super.execute(sql, autoGeneratedKeys);
	}
	
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		this.setLastSql(sql);
		
		return super.execute(sql, columnIndexes);
	}
	
	public boolean execute(String sql, String[] columnNames) throws SQLException {
		this.setLastSql(sql);
		
		return super.execute(sql, columnNames);
	}
	
	/**
	 * 最后执行的SQL
	 */
	public String getLastSql() {
		return this.lastSql;
	}
	
	/**
	 * 最后执行的SQL时间
	 */
	public long getLastSqlTime() {
		return this.lastSqlTime;
	}
	
	/**
	 * 设置最后执行的SQL
	 * @param sql
	 */
	public void setLastSql(String sql) {
		this.lastSql = sql;
		this.conn.setLastSql(sql);
		this.lastSqlTime = System.currentTimeMillis();
	}

	/** 连接 */
	public RsConnection getBaseConnnection() {
		return conn;
	}

	/** 连接 */
	public void setBaseConnnection(RsConnection conn) {
		this.conn = conn;
	}
  
}
