package com.irdstudio.smcenter.core.assembly.socket.client.corba;

/**
* EasyIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from EasyEai.idl
* Monday, March 15, 2004 8:32:43 PM CST
*/

public interface EasyIDLOperations
{
  int commit (byte[] msg, CallBack cb);
  int openFile (String filename, int mode);
  int readFile (int fd, block_tHolder buf);
  int writeFile (int fd, byte[] buf);
  int closeFile (int fd);
} // interface EasyIDLOperations
