package com.irdstudio.smcenter.core.assembly.socket.client.corba;

/**
* EasyIDLHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from EasyEai.idl
* Monday, March 15, 2004 8:32:43 PM CST
*/

abstract public class EasyIDLHelper
{
  private static String  _id = "IDL:EasyIDL:1.0";

  public static void insert (org.omg.CORBA.Any a, EasyIDL that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EasyIDL extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (EasyIDLHelper.id (), "EasyIDL");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EasyIDL read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EasyIDLStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EasyIDL value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static EasyIDL narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EasyIDL)
      return (EasyIDL)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _EasyIDLStub stub = new _EasyIDLStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
