package com.irdstudio.smcenter.core.assembly.socket.client.corba;

/**
* EasyAppIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from EasyEai.idl
* Monday, March 15, 2004 8:32:43 PM CST
*/

public interface EasyAppIDL extends EasyAppIDLOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface EasyAppIDL
