package com.irdstudio.smcenter.core.assembly.socket.client.corba;

/**
* EasyIDLHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from EasyEai.idl
* Monday, March 15, 2004 8:32:43 PM CST
*/

public final class EasyIDLHolder implements org.omg.CORBA.portable.Streamable
{
  public EasyIDL value = null;

  public EasyIDLHolder ()
  {
  }

  public EasyIDLHolder (EasyIDL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EasyIDLHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EasyIDLHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EasyIDLHelper.type ();
  }

}
