package com.irdstudio.smcenter.core.assembly.socket.client.corba;

/**
* EasyAppIDLHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from EasyEai.idl
* Monday, March 15, 2004 8:32:43 PM CST
*/

abstract public class EasyAppIDLHelper
{
  private static String  _id = "IDL:EasyAppIDL:1.0";

  public static void insert (org.omg.CORBA.Any a, EasyAppIDL that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EasyAppIDL extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (EasyAppIDLHelper.id (), "EasyAppIDL");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EasyAppIDL read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EasyAppIDLStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EasyAppIDL value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static EasyAppIDL narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EasyAppIDL)
      return (EasyAppIDL)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _EasyAppIDLStub stub = new _EasyAppIDLStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
