-- CREATE TABLE
CREATE TABLE S_DIC_DAYBAT
(
  ENNAME  VARCHAR2(20) NOT NULL,
  CNNAME  VARCHAR2(600) NOT NULL,
  OPTTYPE VARCHAR2(25) NOT NULL,
  MEMO    VARCHAR2(200),
  FLAG    VARCHAR2(10),
  LEVELS  VARCHAR2(2),
  ORDERID NUMBER,
  MODIFY_DATE VARCHAR(10)
);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE S_DIC_DAYBAT
  ADD CONSTRAINT PK_S_DIC PRIMARY KEY (ENNAME, OPTTYPE);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE S_DIC_DAYBAT
  IS '通用字典';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN S_DIC_DAYBAT.ENNAME  IS '选项值';
COMMENT ON COLUMN S_DIC_DAYBAT.CNNAME  IS '选项名称';
COMMENT ON COLUMN S_DIC_DAYBAT.OPTTYPE  IS '选项类别';
COMMENT ON COLUMN S_DIC_DAYBAT.MEMO  IS '选项描述';
COMMENT ON COLUMN S_DIC_DAYBAT.FLAG  IS '标志';
COMMENT ON COLUMN S_DIC_DAYBAT.LEVELS  IS '级别';
COMMENT ON COLUMN S_DIC_DAYBAT.ORDERID  IS '排序字段';
COMMENT ON COLUMN S_DIC_DAYBAT.MODIFY_DATE  IS '修改日期';

CREATE TABLE BAT_BATCH_INFO_CONFIG
(
  "BATCH_ID"            VARCHAR2(24) NOT NULL,
  "BATCH_NAME"          VARCHAR2(40),
  "SUBS_CODE"           VARCHAR2(16),
  "LAUNCH_TYPE"         CHAR(1),
  "BATCH_CRON_VALUE"    VARCHAR2(40),
  "VALID_DATE"          CHAR(10),
  "EQUALLY_TASK_AMOUNT" NUMBER(11),
  "REMARK"              VARCHAR2(254),
  "IS_RUN_AGAIN"        CHAR(1),
  "AGENT_ID"            VARCHAR2(32)
)
;
COMMENT ON TABLE BAT_BATCH_INFO_CONFIG
  IS '01.批次信息配置';
COMMENT ON COLUMN BAT_BATCH_INFO_CONFIG."BATCH_ID"
  IS '批次标识';
COMMENT ON COLUMN BAT_BATCH_INFO_CONFIG."BATCH_NAME"
  IS '批次名称';
COMMENT ON COLUMN BAT_BATCH_INFO_CONFIG."SUBS_CODE"
  IS '子系统代码';
COMMENT ON COLUMN BAT_BATCH_INFO_CONFIG."LAUNCH_TYPE"
  IS '发起方式';
COMMENT ON COLUMN BAT_BATCH_INFO_CONFIG."BATCH_CRON_VALUE"
  IS '定时周期';
COMMENT ON COLUMN BAT_BATCH_INFO_CONFIG."VALID_DATE"
  IS '生效日期';
COMMENT ON COLUMN BAT_BATCH_INFO_CONFIG."EQUALLY_TASK_AMOUNT"
  IS '任务并发数';
COMMENT ON COLUMN BAT_BATCH_INFO_CONFIG."REMARK"
  IS '备注';
COMMENT ON COLUMN BAT_BATCH_INFO_CONFIG."IS_RUN_AGAIN"
  IS '是否允许重跑';
ALTER TABLE BAT_BATCH_INFO_CONFIG
  ADD PRIMARY KEY (BATCH_ID);

CREATE TABLE BAT_BATCH_STAGE_CONFIG
(
  "STAGE_ID"   VARCHAR2(24) NOT NULL,
  "STAGE_NAME" VARCHAR2(40),
  "BATCH_ID"   VARCHAR2(24) NOT NULL,
  "REMARK"     VARCHAR2(254)
)
;
COMMENT ON TABLE BAT_BATCH_STAGE_CONFIG
  IS '01.批次任务阶段';
COMMENT ON COLUMN BAT_BATCH_STAGE_CONFIG."STAGE_ID"
  IS '阶段编号';
COMMENT ON COLUMN BAT_BATCH_STAGE_CONFIG."STAGE_NAME"
  IS '阶段名称';
COMMENT ON COLUMN BAT_BATCH_STAGE_CONFIG."BATCH_ID"
  IS '批次标识';
COMMENT ON COLUMN BAT_BATCH_STAGE_CONFIG."REMARK"
  IS '备注';
ALTER TABLE BAT_BATCH_STAGE_CONFIG
  ADD PRIMARY KEY (STAGE_ID, BATCH_ID);

CREATE TABLE BAT_INST_BATCH
(
  "BATCH_ID"              VARCHAR2(24) NOT NULL,
  "BATCH_ORDER"           NUMBER(11) NOT NULL,
  "BATCH_NAME"            VARCHAR2(40),
  "BATCH_STATE"           CHAR(1),
  "BATCH_INTERVENE_STATE" CHAR(1),
  "BATCH_DATE"            CHAR(10),
  "START_TIME"            VARCHAR2(24),
  "END_TIME"              VARCHAR2(24),
  "NEED_RUN_COUNT"        NUMBER(11),
  "EXIST_RUN_COUNT"       NUMBER(11),
  "NOT_RUN_COUNT"         NUMBER(11),
  "SUCCEED_RUN_COUNT"     NUMBER(11),
  "FAILD_RUN_COUNT"       NUMBER(11),
  "WARN_RUN_COUNT"        NUMBER(11),
  "SKIP_RUN_COUNT"        NUMBER(11),
  "BATCH_SERIAL_NO"       VARCHAR2(32),
  "REMARK"                VARCHAR2(254),
  "SUBS_CODE"             VARCHAR2(16),
  "COST_TIME"             NUMBER,
  "STAGE_NAME"            VARCHAR2(40),
  "STAGE_ID"              VARCHAR2(24)
)
;
COMMENT ON TABLE BAT_INST_BATCH
  IS '01.批次实例信息';
COMMENT ON COLUMN BAT_INST_BATCH."BATCH_ID"
  IS '批次标识';
COMMENT ON COLUMN BAT_INST_BATCH."BATCH_ORDER"
  IS '批次序号';
COMMENT ON COLUMN BAT_INST_BATCH."BATCH_NAME"
  IS '批次名称';
COMMENT ON COLUMN BAT_INST_BATCH."BATCH_STATE"
  IS '批次状态';
COMMENT ON COLUMN BAT_INST_BATCH."BATCH_INTERVENE_STATE"
  IS '干预状态';
COMMENT ON COLUMN BAT_INST_BATCH."BATCH_DATE"
  IS '批次日期';
COMMENT ON COLUMN BAT_INST_BATCH."START_TIME"
  IS '启动时间';
COMMENT ON COLUMN BAT_INST_BATCH."END_TIME"
  IS '结束时间';
COMMENT ON COLUMN BAT_INST_BATCH."NEED_RUN_COUNT"
  IS '需调度任务数';
COMMENT ON COLUMN BAT_INST_BATCH."EXIST_RUN_COUNT"
  IS '运行中任务数';
COMMENT ON COLUMN BAT_INST_BATCH."NOT_RUN_COUNT"
  IS '未运行任务数';
COMMENT ON COLUMN BAT_INST_BATCH."SUCCEED_RUN_COUNT"
  IS '运行成功任务数';
COMMENT ON COLUMN BAT_INST_BATCH."FAILD_RUN_COUNT"
  IS '运行失败任务数';
COMMENT ON COLUMN BAT_INST_BATCH."WARN_RUN_COUNT"
  IS '运行警告任务数';
COMMENT ON COLUMN BAT_INST_BATCH."SKIP_RUN_COUNT"
  IS '运行置过任务数';
COMMENT ON COLUMN BAT_INST_BATCH."BATCH_SERIAL_NO"
  IS '批次流水号';
COMMENT ON COLUMN BAT_INST_BATCH."REMARK"
  IS '备注';
COMMENT ON COLUMN BAT_INST_BATCH."SUBS_CODE"
  IS '子系统代码';
COMMENT ON COLUMN BAT_INST_BATCH."COST_TIME"
  IS '运行时长';
COMMENT ON COLUMN BAT_INST_BATCH."STAGE_NAME"
  IS '阶段名称';
COMMENT ON COLUMN BAT_INST_BATCH."STAGE_ID"
  IS '阶段编号';
ALTER TABLE BAT_INST_BATCH
  ADD PRIMARY KEY (BATCH_ID, BATCH_ORDER);

CREATE TABLE BAT_INST_BATCH_H
(
  "BATCH_ID"              VARCHAR2(24),
  "BATCH_ORDER"           NUMBER(11),
  "BATCH_NAME"            VARCHAR2(40),
  "SUBS_CODE"             VARCHAR2(16),
  "BATCH_STATE"           CHAR(1),
  "BATCH_INTERVENE_STATE" CHAR(1),
  "STAGE_ID"              VARCHAR2(24),
  "STAGE_NAME"            VARCHAR2(40),
  "BATCH_DATE"            CHAR(10),
  "START_TIME"            VARCHAR2(24),
  "END_TIME"              VARCHAR2(24),
  "COST_TIME"             NUMBER,
  "NEED_RUN_COUNT"        NUMBER(11),
  "EXIST_RUN_COUNT"       NUMBER(11),
  "NOT_RUN_COUNT"         NUMBER(11),
  "SUCCEED_RUN_COUNT"     NUMBER(11),
  "FAILD_RUN_COUNT"       NUMBER(11),
  "WARN_RUN_COUNT"        NUMBER(11),
  "SKIP_RUN_COUNT"        NUMBER(11),
  "BATCH_SERIAL_NO"       VARCHAR2(32) NOT NULL,
  "REMARK"                VARCHAR2(254)
)
;
COMMENT ON TABLE BAT_INST_BATCH_H
  IS '01.批次历史信息';
COMMENT ON COLUMN BAT_INST_BATCH_H."BATCH_ID"
  IS '批次标识';
COMMENT ON COLUMN BAT_INST_BATCH_H."BATCH_ORDER"
  IS '批次序号';
COMMENT ON COLUMN BAT_INST_BATCH_H."BATCH_NAME"
  IS '批次名称';
COMMENT ON COLUMN BAT_INST_BATCH_H."SUBS_CODE"
  IS '子系统代码';
COMMENT ON COLUMN BAT_INST_BATCH_H."BATCH_STATE"
  IS '批次状态';
COMMENT ON COLUMN BAT_INST_BATCH_H."BATCH_INTERVENE_STATE"
  IS '干预状态';
COMMENT ON COLUMN BAT_INST_BATCH_H."STAGE_ID"
  IS '阶段编号';
COMMENT ON COLUMN BAT_INST_BATCH_H."STAGE_NAME"
  IS '阶段名称';
COMMENT ON COLUMN BAT_INST_BATCH_H."BATCH_DATE"
  IS '批次日期';
COMMENT ON COLUMN BAT_INST_BATCH_H."START_TIME"
  IS '启动时间';
COMMENT ON COLUMN BAT_INST_BATCH_H."END_TIME"
  IS '结束时间';
COMMENT ON COLUMN BAT_INST_BATCH_H."COST_TIME"
  IS '运行时长';
COMMENT ON COLUMN BAT_INST_BATCH_H."NEED_RUN_COUNT"
  IS '需调度任务数';
COMMENT ON COLUMN BAT_INST_BATCH_H."EXIST_RUN_COUNT"
  IS '运行中任务数';
COMMENT ON COLUMN BAT_INST_BATCH_H."NOT_RUN_COUNT"
  IS '未运行任务数';
COMMENT ON COLUMN BAT_INST_BATCH_H."SUCCEED_RUN_COUNT"
  IS '运行成功任务数';
COMMENT ON COLUMN BAT_INST_BATCH_H."FAILD_RUN_COUNT"
  IS '运行失败任务数';
COMMENT ON COLUMN BAT_INST_BATCH_H."WARN_RUN_COUNT"
  IS '运行警告任务数';
COMMENT ON COLUMN BAT_INST_BATCH_H."SKIP_RUN_COUNT"
  IS '运行置过任务数';
COMMENT ON COLUMN BAT_INST_BATCH_H."BATCH_SERIAL_NO"
  IS '批次流水号';
COMMENT ON COLUMN BAT_INST_BATCH_H."REMARK"
  IS '备注';
ALTER TABLE BAT_INST_BATCH_H
  ADD PRIMARY KEY (BATCH_SERIAL_NO);

CREATE TABLE BAT_INST_TASK
(
  "BATCH_ID"             VARCHAR2(24) NOT NULL,
  "BATCH_ORDER"          NUMBER(11) NOT NULL,
  "TASK_ID"              VARCHAR2(24) NOT NULL,
  "TASK_NAME"            VARCHAR2(64),
  "STAGE_ID"             VARCHAR2(24),
  "TASK_RUN_STATE"       CHAR(1),
  "TASK_INTERVENE_STATE" CHAR(1),
  "COST_TIME"            NUMBER,
  "START_TIME"           VARCHAR2(24),
  "END_TIME"             VARCHAR2(24),
  "WARN_COUNT"           NUMBER(11),
  "OTHER"                VARCHAR2(40),
  "BATCH_SERIAL_NO"      VARCHAR2(32),
  "STATE_DESC"           VARCHAR2(254),
  "BATCH_DATE"           CHAR(10),
  "STAGE_NAME"           VARCHAR2(40)
)
;
COMMENT ON TABLE BAT_INST_TASK
  IS '02.批次任务实例';
COMMENT ON COLUMN BAT_INST_TASK."BATCH_ID"
  IS '批次标识';
COMMENT ON COLUMN BAT_INST_TASK."BATCH_ORDER"
  IS '批次序号';
COMMENT ON COLUMN BAT_INST_TASK."TASK_ID"
  IS '任务编号';
COMMENT ON COLUMN BAT_INST_TASK."TASK_NAME"
  IS '任务名称';
COMMENT ON COLUMN BAT_INST_TASK."STAGE_ID"
  IS '阶段编号';
COMMENT ON COLUMN BAT_INST_TASK."TASK_RUN_STATE"
  IS '任务执行状态';
COMMENT ON COLUMN BAT_INST_TASK."TASK_INTERVENE_STATE"
  IS '任务干预状态';
COMMENT ON COLUMN BAT_INST_TASK."COST_TIME"
  IS '运行时长';
COMMENT ON COLUMN BAT_INST_TASK."START_TIME"
  IS '启动时间';
COMMENT ON COLUMN BAT_INST_TASK."END_TIME"
  IS '结束时间';
COMMENT ON COLUMN BAT_INST_TASK."WARN_COUNT"
  IS '警告次数';
COMMENT ON COLUMN BAT_INST_TASK."OTHER"
  IS '其它';
COMMENT ON COLUMN BAT_INST_TASK."BATCH_SERIAL_NO"
  IS '批次流水号';
COMMENT ON COLUMN BAT_INST_TASK."STATE_DESC"
  IS '状态描述';
COMMENT ON COLUMN BAT_INST_TASK."BATCH_DATE"
  IS '批次日期';
COMMENT ON COLUMN BAT_INST_TASK."STAGE_NAME"
  IS '阶段名称';
ALTER TABLE BAT_INST_TASK
  ADD PRIMARY KEY (BATCH_ID, BATCH_ORDER, TASK_ID);

CREATE TABLE BAT_INST_TASK_H
(
  "BATCH_ID"             VARCHAR2(24),
  "BATCH_ORDER"          NUMBER(11),
  "TASK_ID"              VARCHAR2(24) NOT NULL,
  "BATCH_DATE"           CHAR(10),
  "TASK_NAME"            VARCHAR2(64),
  "STAGE_ID"             VARCHAR2(24),
  "STAGE_NAME"           VARCHAR2(40),
  "TASK_RUN_STATE"       CHAR(1),
  "TASK_INTERVENE_STATE" CHAR(1),
  "START_TIME"           VARCHAR2(24),
  "END_TIME"             VARCHAR2(24),
  "COST_TIME"            NUMBER,
  "WARN_COUNT"           NUMBER(11),
  "OTHER"                VARCHAR2(40),
  "BATCH_SERIAL_NO"      VARCHAR2(32) NOT NULL,
  "STATE_DESC"           VARCHAR2(254)
)
;
COMMENT ON TABLE BAT_INST_TASK_H
  IS '02.批次任务历史';
COMMENT ON COLUMN BAT_INST_TASK_H."BATCH_ID"
  IS '批次标识';
COMMENT ON COLUMN BAT_INST_TASK_H."BATCH_ORDER"
  IS '批次序号';
COMMENT ON COLUMN BAT_INST_TASK_H."TASK_ID"
  IS '任务编号';
COMMENT ON COLUMN BAT_INST_TASK_H."BATCH_DATE"
  IS '批次日期';
COMMENT ON COLUMN BAT_INST_TASK_H."TASK_NAME"
  IS '任务名称';
COMMENT ON COLUMN BAT_INST_TASK_H."STAGE_ID"
  IS '阶段编号';
COMMENT ON COLUMN BAT_INST_TASK_H."STAGE_NAME"
  IS '阶段名称';
COMMENT ON COLUMN BAT_INST_TASK_H."TASK_RUN_STATE"
  IS '任务执行状态';
COMMENT ON COLUMN BAT_INST_TASK_H."TASK_INTERVENE_STATE"
  IS '任务干预状态';
COMMENT ON COLUMN BAT_INST_TASK_H."START_TIME"
  IS '启动时间';
COMMENT ON COLUMN BAT_INST_TASK_H."END_TIME"
  IS '结束时间';
COMMENT ON COLUMN BAT_INST_TASK_H."COST_TIME"
  IS '运行时长';
COMMENT ON COLUMN BAT_INST_TASK_H."WARN_COUNT"
  IS '警告次数';
COMMENT ON COLUMN BAT_INST_TASK_H."OTHER"
  IS '其它';
COMMENT ON COLUMN BAT_INST_TASK_H."BATCH_SERIAL_NO"
  IS '批次流水号';
COMMENT ON COLUMN BAT_INST_TASK_H."STATE_DESC"
  IS '状态描述';
ALTER TABLE BAT_INST_TASK_H
  ADD PRIMARY KEY (TASK_ID, BATCH_SERIAL_NO);

CREATE TABLE BAT_TASK_LOCALE_CONFIG
(
  "LOCALE_ID"   VARCHAR2(24) NOT NULL,
  "LOCALE_NAME" VARCHAR2(40),
  "LOCALE_TYPE" CHAR(1),
  "LOCALE_IP"   VARCHAR2(24),
  "LOCALE_PORT" VARCHAR2(8),
  "LOGIN_TYPE"  CHAR(1),
  "LOGIN_USER"  VARCHAR2(24),
  "LOGIN_PWD"   VARCHAR2(40),
  "REMARK"      VARCHAR2(254)
)
;
COMMENT ON TABLE BAT_TASK_LOCALE_CONFIG
  IS '02.执行场所配置';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG."LOCALE_ID"
  IS '执行场所编号';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG."LOCALE_NAME"
  IS '执行场所名称';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG."LOCALE_TYPE"
  IS '场所类型';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG."LOCALE_IP"
  IS '场所IP';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG."LOCALE_PORT"
  IS '场所端口';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG."LOGIN_TYPE"
  IS '登录方式';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG."LOGIN_USER"
  IS '登录用户名';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG."LOGIN_PWD"
  IS '登录密码';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG."REMARK"
  IS '备注';
ALTER TABLE BAT_TASK_LOCALE_CONFIG
  ADD PRIMARY KEY (LOCALE_ID);

CREATE TABLE BAT_TASK_LOCALE_CONFIG_COPY
(
  "LOCALE_ID"   VARCHAR2(24) NOT NULL,
  "LOCALE_NAME" VARCHAR2(40),
  "LOCALE_TYPE" CHAR(1),
  "LOCALE_IP"   VARCHAR2(24),
  "LOCALE_PORT" VARCHAR2(8),
  "LOGIN_TYPE"  CHAR(1),
  "LOGIN_USER"  VARCHAR2(24),
  "LOGIN_PWD"   VARCHAR2(40),
  "REMARK"      VARCHAR2(254)
)
;
COMMENT ON TABLE BAT_TASK_LOCALE_CONFIG_COPY
  IS '02.执行场所配置';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG_COPY."LOCALE_ID"
  IS '执行场所编号';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG_COPY."LOCALE_NAME"
  IS '执行场所名称';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG_COPY."LOCALE_TYPE"
  IS '场所类型';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG_COPY."LOCALE_IP"
  IS '场所IP';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG_COPY."LOCALE_PORT"
  IS '场所端口';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG_COPY."LOGIN_TYPE"
  IS '登录方式';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG_COPY."LOGIN_USER"
  IS '登录用户名';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG_COPY."LOGIN_PWD"
  IS '登录密码';
COMMENT ON COLUMN BAT_TASK_LOCALE_CONFIG_COPY."REMARK"
  IS '备注';
ALTER TABLE BAT_TASK_LOCALE_CONFIG_COPY
  ADD PRIMARY KEY (LOCALE_ID);

CREATE TABLE BAT_TASK_UNIT_CONFIG
(
  "TASK_NAME"           VARCHAR2(64),
  "TASK_ID"             VARCHAR2(24) NOT NULL,
  "PREVIOUS_TASK_ID"    VARCHAR2(24),
  "BATCH_ID"            VARCHAR2(24),
  "STAGE_ID"            VARCHAR2(24),
  "LOCALE_ID"           VARCHAR2(24),
  "PLUGIN_ID"           NUMBER(11),
  "PLUGIN_SOURCE_TYPE"  CHAR(1),
  "PLUGIN_PARA_FLAG"    VARCHAR2(40),
  "TASK_PRI"            CHAR(1),
  "TASK_RUN_TYPE"       CHAR(1),
  "TASK_CYCLE_TYPE"     CHAR(1),
  "TASK_CRON_VALUE"     VARCHAR2(40),
  "TASK_DELAY_TIME"     NUMBER(11),
  "TASK_SKIP_TACTIC"    CHAR(1),
  "AGAIN_RUN_SPACE"     NUMBER(11),
  "TASK_ESTIMATE_TIME"  NUMBER(11),
  "TASK_USE_STATE"      CHAR(1),
  "REMARK"              VARCHAR2(254),
  "MAX_RUN_COUNT"       NUMBER(11),
  "TASK_TIMEOUT_TIME"   NUMBER(11),
  "TASK_TIMEOUT_TACTIC" CHAR(1),
  "SUBS_DS_CODE"        VARCHAR2(40),
  "TASK_USE_AREA"       CHAR(1),
  "PLUGIN_TYPE"         CHAR(1),
  "MAX_WAIT_TIME"       NUMBER(11),
  "CYCLE_INTEVAL"       NUMBER(11)
)
;
COMMENT ON TABLE BAT_TASK_UNIT_CONFIG
  IS '02.批次任务配置';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."TASK_NAME"
  IS '任务名称';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."TASK_ID"
  IS '任务编号';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."PREVIOUS_TASK_ID"
  IS '前一任务编号';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."BATCH_ID"
  IS '批次标识';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."STAGE_ID"
  IS '阶段编号';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."LOCALE_ID"
  IS '执行场所编号';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."PLUGIN_ID"
  IS '应用插件ID';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."PLUGIN_SOURCE_TYPE"
  IS '插件配置数据来源方式';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."PLUGIN_PARA_FLAG"
  IS '插件配置数据标识';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."TASK_PRI"
  IS '任务优先级';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."TASK_RUN_TYPE"
  IS '任务执行类型';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."TASK_CYCLE_TYPE"
  IS '任务周期类型';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."TASK_CRON_VALUE"
  IS '任务定时周期';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."TASK_DELAY_TIME"
  IS '任务延时执行时间(秒)';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."TASK_SKIP_TACTIC"
  IS '任务失败跳过策略';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."AGAIN_RUN_SPACE"
  IS '任务重复调起时间间隔(秒)';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."TASK_ESTIMATE_TIME"
  IS '任务预计执行时间(秒)';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."TASK_USE_STATE"
  IS '任务使用状态';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."REMARK"
  IS '备注';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."MAX_RUN_COUNT"
  IS '任务最大重复调起次数';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."TASK_TIMEOUT_TIME"
  IS '任务运行超时时间(秒)';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."TASK_TIMEOUT_TACTIC"
  IS '任务运行超时策略';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."SUBS_DS_CODE"
  IS '子系统数据源代码';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."TASK_USE_AREA"
  IS '任务使用场景';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."PLUGIN_TYPE"
  IS '应用插件类型';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."MAX_WAIT_TIME"
  IS '最长等待时间';
COMMENT ON COLUMN BAT_TASK_UNIT_CONFIG."CYCLE_INTEVAL"
  IS '轮询间隔(秒)';
ALTER TABLE BAT_TASK_UNIT_CONFIG
  ADD PRIMARY KEY (TASK_ID);

CREATE TABLE PLUGIN_CHECK_CONF
(
  "PLUGIN_CONF_ID"      VARCHAR2(24) NOT NULL,
  "CONF_SORT"           NUMBER(11) NOT NULL,
  "CHECK_ITEM_NAME"     VARCHAR2(64),
  "CHECK_ITEM_SQL"      NCLOB,
  "CHECK_SUC_CONDITION" VARCHAR2(254),
  "CHECK_ERR_DESC"      VARCHAR2(254),
  "CHECK_FAILD_DEAL"    CHAR(1),
  "VALID_DATE"          CHAR(10),
  "INVALID_DATE"        CHAR(10),
  "LAST_MODIFY_DATE"    CHAR(10)
)
;
COMMENT ON TABLE PLUGIN_CHECK_CONF
  IS '01.数据检查配置表';
COMMENT ON COLUMN PLUGIN_CHECK_CONF."PLUGIN_CONF_ID"
  IS '配置标识符';
COMMENT ON COLUMN PLUGIN_CHECK_CONF."CONF_SORT"
  IS '配置顺序';
COMMENT ON COLUMN PLUGIN_CHECK_CONF."CHECK_ITEM_NAME"
  IS '检查项名称';
COMMENT ON COLUMN PLUGIN_CHECK_CONF."CHECK_ITEM_SQL"
  IS '检查项SQL';
COMMENT ON COLUMN PLUGIN_CHECK_CONF."CHECK_SUC_CONDITION"
  IS '检查成功条件';
COMMENT ON COLUMN PLUGIN_CHECK_CONF."CHECK_ERR_DESC"
  IS '错误描述';
COMMENT ON COLUMN PLUGIN_CHECK_CONF."CHECK_FAILD_DEAL"
  IS '检查失败处理方式';
COMMENT ON COLUMN PLUGIN_CHECK_CONF."VALID_DATE"
  IS '生效日期';
COMMENT ON COLUMN PLUGIN_CHECK_CONF."INVALID_DATE"
  IS '失效日期';
COMMENT ON COLUMN PLUGIN_CHECK_CONF."LAST_MODIFY_DATE"
  IS '最后更新日期';
ALTER TABLE PLUGIN_CHECK_CONF
  ADD PRIMARY KEY (PLUGIN_CONF_ID, CONF_SORT);

CREATE TABLE PLUGIN_DEFINE
(
  "PLUGIN_ID"         NUMBER(11) NOT NULL,
  "PLUGIN_NAME"       VARCHAR2(64),
  "PLUGIN_CLASS"      VARCHAR2(254),
  "PLUGIN_DESC"       VARCHAR2(254),
  "NEED_OTHER_DS_VAR" CHAR(1),
  "PLUGIN_CONFIG_URL" VARCHAR2(64),
  "PLUGIN_CATALOG"    CHAR(2)
)
;
COMMENT ON TABLE PLUGIN_DEFINE
  IS '01.应用插件信息';
COMMENT ON COLUMN PLUGIN_DEFINE."PLUGIN_ID"
  IS '应用插件ID';
COMMENT ON COLUMN PLUGIN_DEFINE."PLUGIN_NAME"
  IS '应用插件名称';
COMMENT ON COLUMN PLUGIN_DEFINE."PLUGIN_CLASS"
  IS '应用插件实现类';
COMMENT ON COLUMN PLUGIN_DEFINE."PLUGIN_DESC"
  IS '应用插件描述';
COMMENT ON COLUMN PLUGIN_DEFINE."NEED_OTHER_DS_VAR"
  IS '是否需要其它数据源变量';
COMMENT ON COLUMN PLUGIN_DEFINE."PLUGIN_CONFIG_URL"
  IS '应用插件配置地址';
COMMENT ON COLUMN PLUGIN_DEFINE."PLUGIN_CATALOG"
  IS '应用插件分类';
ALTER TABLE PLUGIN_DEFINE
  ADD PRIMARY KEY (PLUGIN_ID);

CREATE TABLE PLUGIN_EXCEL_CONF
(
  "PLUGIN_CONF_ID"   VARCHAR2(24) NOT NULL,
  "CONF_SORT"        NUMBER(11) NOT NULL,
  "EXCEL_OPER_TYPE"  CHAR(2),
  "PARAM_KEY_VALUE"  VARCHAR2(512),
  "CONFIGURE_FILE"   VARCHAR2(128),
  "FAILD_DEAL"       CHAR(1),
  "LAST_MODIFY_DATE" CHAR(10)
)
;
COMMENT ON TABLE PLUGIN_EXCEL_CONF
  IS '01.EXCEL操作配置表';
COMMENT ON COLUMN PLUGIN_EXCEL_CONF."PLUGIN_CONF_ID"
  IS '配置标识符';
COMMENT ON COLUMN PLUGIN_EXCEL_CONF."CONF_SORT"
  IS '配置顺序';
COMMENT ON COLUMN PLUGIN_EXCEL_CONF."EXCEL_OPER_TYPE"
  IS 'EXCEL操作类型';
COMMENT ON COLUMN PLUGIN_EXCEL_CONF."PARAM_KEY_VALUE"
  IS '参数键值对';
COMMENT ON COLUMN PLUGIN_EXCEL_CONF."CONFIGURE_FILE"
  IS 'EXCEL操作配置文件';
COMMENT ON COLUMN PLUGIN_EXCEL_CONF."FAILD_DEAL"
  IS '失败处理方式';
COMMENT ON COLUMN PLUGIN_EXCEL_CONF."LAST_MODIFY_DATE"
  IS '最后更新日期';
ALTER TABLE PLUGIN_EXCEL_CONF
  ADD PRIMARY KEY (PLUGIN_CONF_ID, CONF_SORT);

CREATE TABLE PLUGIN_EXEC_LOG
(
  "BATCH_SN"           VARCHAR2(32),
  "PLUGIN_ID"          NUMBER(11),
  "PLUGIN_NAME"        VARCHAR2(64),
  "ACTION_NAME"        VARCHAR2(254),
  "ACTION_RESULT"      CHAR(1),
  "ACTION_DETAIL_INFO" NCLOB,
  "TASK_ID"            VARCHAR2(24),
  "TASK_NAME"          VARCHAR2(64),
  "RECORD_TIME"        VARCHAR2(24)
)
;
COMMENT ON TABLE PLUGIN_EXEC_LOG
  IS '02.应用插件执行日志';
COMMENT ON COLUMN PLUGIN_EXEC_LOG."BATCH_SN"
  IS '批次流水号';
COMMENT ON COLUMN PLUGIN_EXEC_LOG."PLUGIN_ID"
  IS '应用插件ID';
COMMENT ON COLUMN PLUGIN_EXEC_LOG."PLUGIN_NAME"
  IS '应用插件名称';
COMMENT ON COLUMN PLUGIN_EXEC_LOG."ACTION_NAME"
  IS '操作名称';
COMMENT ON COLUMN PLUGIN_EXEC_LOG."ACTION_RESULT"
  IS '操作结果';
COMMENT ON COLUMN PLUGIN_EXEC_LOG."ACTION_DETAIL_INFO"
  IS '操作详情';
COMMENT ON COLUMN PLUGIN_EXEC_LOG."TASK_ID"
  IS '任务编号';
COMMENT ON COLUMN PLUGIN_EXEC_LOG."TASK_NAME"
  IS '任务名称';
COMMENT ON COLUMN PLUGIN_EXEC_LOG."RECORD_TIME"
  IS '记录时间';

CREATE TABLE PLUGIN_EXPORT_CONF
(
  "PLUGIN_CONF_ID"  VARCHAR2(24) NOT NULL,
  "CONF_SORT"       NUMBER(11) NOT NULL,
  "EXPORT_MODE"     CHAR(2),
  "EXPORT_TARGET"   VARCHAR2(512),
  "EXPORT_TO_FILE"  VARCHAR2(100),
  "FIELD_SEPARATOR" VARCHAR2(16),
  "FILE_CHARSET"    VARCHAR2(16)
)
;
COMMENT ON TABLE PLUGIN_EXPORT_CONF
  IS '01.导出为文本文件插件';
COMMENT ON COLUMN PLUGIN_EXPORT_CONF."PLUGIN_CONF_ID"
  IS '配置标识符';
COMMENT ON COLUMN PLUGIN_EXPORT_CONF."CONF_SORT"
  IS '配置顺序';
COMMENT ON COLUMN PLUGIN_EXPORT_CONF."EXPORT_MODE"
  IS '数据导出方式';
COMMENT ON COLUMN PLUGIN_EXPORT_CONF."EXPORT_TARGET"
  IS '数据表/SQL语句';
COMMENT ON COLUMN PLUGIN_EXPORT_CONF."EXPORT_TO_FILE"
  IS '文件存放路径';
COMMENT ON COLUMN PLUGIN_EXPORT_CONF."FIELD_SEPARATOR"
  IS '字段分隔符';
COMMENT ON COLUMN PLUGIN_EXPORT_CONF."FILE_CHARSET"
  IS '文件编码格式';
ALTER TABLE PLUGIN_EXPORT_CONF
  ADD PRIMARY KEY (PLUGIN_CONF_ID, CONF_SORT);

CREATE TABLE PLUGIN_FILEOP_CONF
(
  "PLUGIN_CONF_ID"   VARCHAR2(24) NOT NULL,
  "CONF_SORT"        NUMBER(11) NOT NULL,
  "FILE_OP"          CHAR(2),
  "OP_CYCLE_DAY"     NUMBER(11),
  "LAST_OP_DATE"     CHAR(10),
  "LAST_MODIFY_DATE" CHAR(10),
  "DISTANCE_DAY"     NUMBER(11),
  "FILE_TARGET"      VARCHAR2(128)
)
;
COMMENT ON TABLE PLUGIN_FILEOP_CONF
  IS '01.文件操作配置';
COMMENT ON COLUMN PLUGIN_FILEOP_CONF."PLUGIN_CONF_ID"
  IS '配置标识符';
COMMENT ON COLUMN PLUGIN_FILEOP_CONF."CONF_SORT"
  IS '配置顺序';
COMMENT ON COLUMN PLUGIN_FILEOP_CONF."FILE_OP"
  IS '文件操作';
COMMENT ON COLUMN PLUGIN_FILEOP_CONF."OP_CYCLE_DAY"
  IS '操作周期';
COMMENT ON COLUMN PLUGIN_FILEOP_CONF."LAST_OP_DATE"
  IS '上次操作日期';
COMMENT ON COLUMN PLUGIN_FILEOP_CONF."LAST_MODIFY_DATE"
  IS '最后更新日期';
COMMENT ON COLUMN PLUGIN_FILEOP_CONF."DISTANCE_DAY"
  IS '目标距离(天)';
COMMENT ON COLUMN PLUGIN_FILEOP_CONF."FILE_TARGET"
  IS '目标文件';
ALTER TABLE PLUGIN_FILEOP_CONF
  ADD PRIMARY KEY (PLUGIN_CONF_ID, CONF_SORT);

CREATE TABLE PLUGIN_JOB_CONF
(
  "PLUGIN_CONF_ID"   VARCHAR2(24) NOT NULL,
  "CONF_SORT"        NUMBER(11) NOT NULL,
  "JOB_NAME"         VARCHAR2(32),
  "SQL_PURPOSE"      CHAR(1),
  "SQL_CONTENT"      NCLOB,
  "PARAM_GROUP_ID"   VARCHAR2(40),
  "JOB_FAILD_DEAL"   CHAR(1),
  "LAST_MODIFY_DATE" CHAR(10),
  "JOB_IMPLEMENT"    VARCHAR2(128)
)
;
COMMENT ON TABLE PLUGIN_JOB_CONF
  IS '01.数据作业配置';
COMMENT ON COLUMN PLUGIN_JOB_CONF."PLUGIN_CONF_ID"
  IS '配置标识符';
COMMENT ON COLUMN PLUGIN_JOB_CONF."CONF_SORT"
  IS '配置顺序';
COMMENT ON COLUMN PLUGIN_JOB_CONF."JOB_NAME"
  IS '作业名称';
COMMENT ON COLUMN PLUGIN_JOB_CONF."SQL_PURPOSE"
  IS 'SQL脚本用途';
COMMENT ON COLUMN PLUGIN_JOB_CONF."SQL_CONTENT"
  IS 'SQL脚本';
COMMENT ON COLUMN PLUGIN_JOB_CONF."PARAM_GROUP_ID"
  IS '参数组标识';
COMMENT ON COLUMN PLUGIN_JOB_CONF."JOB_FAILD_DEAL"
  IS '作业失败处理方式';
COMMENT ON COLUMN PLUGIN_JOB_CONF."LAST_MODIFY_DATE"
  IS '最后更新日期';
COMMENT ON COLUMN PLUGIN_JOB_CONF."JOB_IMPLEMENT"
  IS '作业实现';
ALTER TABLE PLUGIN_JOB_CONF
  ADD PRIMARY KEY (PLUGIN_CONF_ID, CONF_SORT);

CREATE TABLE PLUGIN_JOB_PARAM
(
  "PARAM_GROUP_ID"  VARCHAR2(40) NOT NULL,
  "JOB_PARAM_NAME"  VARCHAR2(32) NOT NULL,
  "JOB_PARAM_VALUE" VARCHAR2(512)
)
;
COMMENT ON TABLE PLUGIN_JOB_PARAM
  IS '02.数据作业参数配置';
COMMENT ON COLUMN PLUGIN_JOB_PARAM."PARAM_GROUP_ID"
  IS '参数组标识';
COMMENT ON COLUMN PLUGIN_JOB_PARAM."JOB_PARAM_NAME"
  IS '作业参数名称';
COMMENT ON COLUMN PLUGIN_JOB_PARAM."JOB_PARAM_VALUE"
  IS '作业参数值';
ALTER TABLE PLUGIN_JOB_PARAM
  ADD PRIMARY KEY (PARAM_GROUP_ID, JOB_PARAM_NAME);

CREATE TABLE PLUGIN_LOAD_CONF
(
  "TABLE_NAME"       VARCHAR2(38) NOT NULL,
  "TABLE_CNNAME"     VARCHAR2(80),
  "TABLE_TYPE"       CHAR(1),
  "TABLE_LOAD_MODE"  CHAR(1),
  "UP_SYSNAME"       VARCHAR2(80),
  "LOAD_FROM_FILE"   VARCHAR2(100),
  "FILE_ROW_FLAG"    CHAR(1),
  "LOAD_WARN_FLAG"   CHAR(1),
  "DIFF_COMP_METHOD" CHAR(2),
  "LIMIT_PERCENT"    NUMBER(11),
  "DIFF_DEAL_METHOD" CHAR(1),
  "LAST_MODIFY_DATE" CHAR(10),
  "PLUGIN_CONF_ID"   VARCHAR2(24) NOT NULL,
  "CONF_SORT"        NUMBER(11),
  "LOAD_SEPARATOR"   VARCHAR2(16),
  "BEFORE_LOAD_SQL"  NCLOB,
  "AFTER_LOAD_SQL"   NCLOB,
  "FILE_CHARSET"     VARCHAR2(16),
  "LOAD_BUFFER_SIZE" NUMBER(11),
  "LOAD_FAILD_DEAL"  CHAR(1),
  "LOAD_FIELDS"      NCLOB,
  "CREATE_TABLE_DDL" NCLOB
)
;
COMMENT ON TABLE PLUGIN_LOAD_CONF
  IS '01.数据装载配置表';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."TABLE_NAME"
  IS '数据库表名';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."TABLE_CNNAME"
  IS '表中文名称';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."TABLE_TYPE"
  IS '数据表类型';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."TABLE_LOAD_MODE"
  IS '数据装载方式';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."UP_SYSNAME"
  IS '供数系统名称';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."LOAD_FROM_FILE"
  IS '文件路径';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."FILE_ROW_FLAG"
  IS '是否允许条数为零';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."LOAD_WARN_FLAG"
  IS '是否忽略警告';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."DIFF_COMP_METHOD"
  IS '差异比较方式';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."LIMIT_PERCENT"
  IS '比较阀值(%)';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."DIFF_DEAL_METHOD"
  IS '差异处理方式';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."LAST_MODIFY_DATE"
  IS '最后更新日期';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."PLUGIN_CONF_ID"
  IS '配置标识符';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."CONF_SORT"
  IS '配置顺序';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."LOAD_SEPARATOR"
  IS '字段分隔符';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."BEFORE_LOAD_SQL"
  IS '装载前执行语句';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."AFTER_LOAD_SQL"
  IS '装载后执行语句';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."FILE_CHARSET"
  IS '文件编码格式';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."LOAD_BUFFER_SIZE"
  IS '缓冲区大小(K)';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."LOAD_FAILD_DEAL"
  IS '装载失败处理方式';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."LOAD_FIELDS"
  IS '指定字段';
COMMENT ON COLUMN PLUGIN_LOAD_CONF."CREATE_TABLE_DDL"
  IS '建表语句';
ALTER TABLE PLUGIN_LOAD_CONF
  ADD PRIMARY KEY (TABLE_NAME, PLUGIN_CONF_ID);

CREATE TABLE PLUGIN_LOAD_RESULT
(
  "BATCH_SERIAL_NO" VARCHAR2(32) NOT NULL,
  "BATCH_DATE"      CHAR(10),
  "TABLE_NAME"      VARCHAR2(38) NOT NULL,
  "TABLE_CNNAME"    VARCHAR2(80),
  "TABLE_TYPE"      CHAR(1),
  "UP_SYSNAME"      VARCHAR2(80),
  "TABLE_LOAD_MODE" CHAR(1),
  "LOAD_FROM_FILE"  VARCHAR2(100),
  "FILE_SIZE"       NUMBER,
  "START_TIME"      VARCHAR2(24),
  "END_TIME"        VARCHAR2(24),
  "COST_TIME"       NUMBER,
  "READ_ROWS"       NUMBER(11),
  "LOAD_ROWS"       NUMBER(11),
  "REJECT_ROWS"     NUMBER(11),
  "REMARK"          VARCHAR2(254),
  "LOAD_RESULT"     CHAR(1),
  "BATCH_ID"        VARCHAR2(24)
)
;
COMMENT ON TABLE PLUGIN_LOAD_RESULT
  IS '02.数据装载结果表';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."BATCH_SERIAL_NO"
  IS '批次流水号';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."BATCH_DATE"
  IS '批次日期';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."TABLE_NAME"
  IS '数据库表名';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."TABLE_CNNAME"
  IS '表中文名称';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."TABLE_TYPE"
  IS '数据表类型';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."UP_SYSNAME"
  IS '供数系统名称';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."TABLE_LOAD_MODE"
  IS '数据装载方式';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."LOAD_FROM_FILE"
  IS '文件路径';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."FILE_SIZE"
  IS '文件大小';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."START_TIME"
  IS '启动时间';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."END_TIME"
  IS '结束时间';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."COST_TIME"
  IS '运行时长';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."READ_ROWS"
  IS '读入条数';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."LOAD_ROWS"
  IS '装入条数';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."REJECT_ROWS"
  IS '拒绝条数';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."REMARK"
  IS '备注';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."LOAD_RESULT"
  IS '导数结果';
COMMENT ON COLUMN PLUGIN_LOAD_RESULT."BATCH_ID"
  IS '批次标识';
ALTER TABLE PLUGIN_LOAD_RESULT
  ADD PRIMARY KEY (BATCH_SERIAL_NO, TABLE_NAME);

CREATE TABLE PLUGIN_REFORM_CONF
(
  "PLUGIN_CONF_ID"      VARCHAR2(24) NOT NULL,
  "CONF_SORT"           NUMBER(11) NOT NULL,
  "REFORM_TABLE_SCHEMA" VARCHAR2(24),
  "REFORM_TABLE_NAME"   VARCHAR2(38),
  "REFORM_GROUP_ID"     VARCHAR2(24),
  "REFORM_CYCLE_DAY"    NUMBER(11),
  "LAST_REFORM_DATE"    CHAR(10),
  "RSV_OPTION"          VARCHAR2(24),
  "VALID_DATE"          CHAR(10),
  "INVALID_DATE"        CHAR(10),
  "LAST_MODIFY_DATE"    CHAR(10)
)
;
COMMENT ON TABLE PLUGIN_REFORM_CONF
  IS '01.数据表重整配置表';
COMMENT ON COLUMN PLUGIN_REFORM_CONF."PLUGIN_CONF_ID"
  IS '配置标识符';
COMMENT ON COLUMN PLUGIN_REFORM_CONF."CONF_SORT"
  IS '配置顺序';
COMMENT ON COLUMN PLUGIN_REFORM_CONF."REFORM_TABLE_SCHEMA"
  IS '表所属模式';
COMMENT ON COLUMN PLUGIN_REFORM_CONF."REFORM_TABLE_NAME"
  IS '重整表名称';
COMMENT ON COLUMN PLUGIN_REFORM_CONF."REFORM_GROUP_ID"
  IS '重整组ID';
COMMENT ON COLUMN PLUGIN_REFORM_CONF."REFORM_CYCLE_DAY"
  IS '重整周期';
COMMENT ON COLUMN PLUGIN_REFORM_CONF."LAST_REFORM_DATE"
  IS '上次重整日期';
COMMENT ON COLUMN PLUGIN_REFORM_CONF."RSV_OPTION"
  IS '备用选项';
COMMENT ON COLUMN PLUGIN_REFORM_CONF."VALID_DATE"
  IS '生效日期';
COMMENT ON COLUMN PLUGIN_REFORM_CONF."INVALID_DATE"
  IS '失效日期';
COMMENT ON COLUMN PLUGIN_REFORM_CONF."LAST_MODIFY_DATE"
  IS '最后更新日期';
ALTER TABLE PLUGIN_REFORM_CONF
  ADD PRIMARY KEY (PLUGIN_CONF_ID, CONF_SORT);

CREATE TABLE PLUGIN_SC_CONF
(
  "PLUGIN_CONF_ID"   VARCHAR2(24),
  "CONF_SORT"        NUMBER(11),
  "SC_DESC"          VARCHAR2(80),
  "FUNC_CODE"        NUMBER(11),
  "FUNC_PARAMS"      NCLOB,
  "CHECK_FAILD_DEAL" CHAR(1)
)
;
COMMENT ON TABLE PLUGIN_SC_CONF
  IS '01.转存清数配置';
COMMENT ON COLUMN PLUGIN_SC_CONF."PLUGIN_CONF_ID"
  IS '配置标识符';
COMMENT ON COLUMN PLUGIN_SC_CONF."CONF_SORT"
  IS '配置顺序';
COMMENT ON COLUMN PLUGIN_SC_CONF."SC_DESC"
  IS '转存清数描述';
COMMENT ON COLUMN PLUGIN_SC_CONF."FUNC_CODE"
  IS '指令/函数编号';
COMMENT ON COLUMN PLUGIN_SC_CONF."FUNC_PARAMS"
  IS '指令/函数参数';
COMMENT ON COLUMN PLUGIN_SC_CONF."CHECK_FAILD_DEAL"
  IS '检查失败处理方式';

CREATE TABLE PLUGIN_SC_FUNC
(
  "FUNC_CODE" NUMBER(11),
  "FUNC_NAME" VARCHAR2(80)
)
;
COMMENT ON TABLE PLUGIN_SC_FUNC
  IS '02.转存清数指令/函数';
COMMENT ON COLUMN PLUGIN_SC_FUNC."FUNC_CODE"
  IS '指令/函数编号';
COMMENT ON COLUMN PLUGIN_SC_FUNC."FUNC_NAME"
  IS '指令/函数名称';

CREATE TABLE PLUGIN_SERVICE_CONF
(
  "PLUGIN_CONF_ID"    VARCHAR2(24) NOT NULL,
  "CONF_SORT"         NUMBER(11) NOT NULL,
  "SERVICE_ID"        VARCHAR2(80),
  "SERVICE_NAME"      VARCHAR2(128),
  "SERVICE_INTERFACE" VARCHAR2(128),
  "SERVICE_METHOD"    VARCHAR2(128),
  "RETURN_TYPE"       VARCHAR2(128),
  "PARAM_GROUP_ID"    VARCHAR2(40),
  "VERSION"           VARCHAR2(8),
  "SERVICE_GROUP"     VARCHAR2(16),
  "TIMEOUT"           NUMBER(11)
)
;
COMMENT ON TABLE PLUGIN_SERVICE_CONF
  IS '服务调用插件';
COMMENT ON COLUMN PLUGIN_SERVICE_CONF."PLUGIN_CONF_ID"
  IS '配置标识符';
COMMENT ON COLUMN PLUGIN_SERVICE_CONF."CONF_SORT"
  IS '配置顺序';
COMMENT ON COLUMN PLUGIN_SERVICE_CONF."SERVICE_ID"
  IS '服务ID';
COMMENT ON COLUMN PLUGIN_SERVICE_CONF."SERVICE_NAME"
  IS '服务名称';
COMMENT ON COLUMN PLUGIN_SERVICE_CONF."SERVICE_INTERFACE"
  IS '服务接口类';
COMMENT ON COLUMN PLUGIN_SERVICE_CONF."SERVICE_METHOD"
  IS '服务实现方法';
COMMENT ON COLUMN PLUGIN_SERVICE_CONF."RETURN_TYPE"
  IS '方法返回类型';
COMMENT ON COLUMN PLUGIN_SERVICE_CONF."PARAM_GROUP_ID"
  IS '参数组标识';
COMMENT ON COLUMN PLUGIN_SERVICE_CONF."VERSION"
  IS '服务版本';
COMMENT ON COLUMN PLUGIN_SERVICE_CONF."SERVICE_GROUP"
  IS '服务组别';
COMMENT ON COLUMN PLUGIN_SERVICE_CONF."TIMEOUT"
  IS '调用超时时间';
ALTER TABLE PLUGIN_SERVICE_CONF
  ADD PRIMARY KEY (PLUGIN_CONF_ID, CONF_SORT);

CREATE TABLE PLUGIN_SERVICE_PARAM
(
  "PARAM_GROUP_ID"      VARCHAR2(40) NOT NULL,
  "SERVICE_PARAM_NAME"  VARCHAR2(32) NOT NULL,
  "SERVICE_PARAM_TYPE"  VARCHAR2(128) NOT NULL,
  "SERVICE_PARAM_VALUE" VARCHAR2(512)
)
;
COMMENT ON TABLE PLUGIN_SERVICE_PARAM
  IS '服务参数配置';
COMMENT ON COLUMN PLUGIN_SERVICE_PARAM."PARAM_GROUP_ID"
  IS '参数组标识';
COMMENT ON COLUMN PLUGIN_SERVICE_PARAM."SERVICE_PARAM_NAME"
  IS '服务参数名称';
COMMENT ON COLUMN PLUGIN_SERVICE_PARAM."SERVICE_PARAM_TYPE"
  IS '服务参数类型';
COMMENT ON COLUMN PLUGIN_SERVICE_PARAM."SERVICE_PARAM_VALUE"
  IS '服务参数值';
ALTER TABLE PLUGIN_SERVICE_PARAM
  ADD PRIMARY KEY (PARAM_GROUP_ID, SERVICE_PARAM_NAME);

CREATE TABLE PLUGIN_SYSUPD_CONF
(
  "PLUGIN_CONF_ID" VARCHAR2(24) NOT NULL,
  "CONF_SORT"      NUMBER(11) NOT NULL,
  "SYSUPD_ACTION"  CHAR(2)
)
;
COMMENT ON TABLE PLUGIN_SYSUPD_CONF
  IS '01.系统信息更新配置表';
COMMENT ON COLUMN PLUGIN_SYSUPD_CONF."PLUGIN_CONF_ID"
  IS '配置标识符';
COMMENT ON COLUMN PLUGIN_SYSUPD_CONF."CONF_SORT"
  IS '配置顺序';
COMMENT ON COLUMN PLUGIN_SYSUPD_CONF."SYSUPD_ACTION"
  IS '系统信息更新动作';
ALTER TABLE PLUGIN_SYSUPD_CONF
  ADD PRIMARY KEY (PLUGIN_CONF_ID, CONF_SORT);

CREATE TABLE PLUGIN_WT_CONDITION
(
  "PLUGIN_CONF_ID"      VARCHAR2(24) NOT NULL,
  "CONF_SORT"           NUMBER(11) NOT NULL,
  "CHECK_ITEM_NAME"     VARCHAR2(64),
  "CHECK_ITEM_SQL"      NCLOB,
  "CHECK_SUC_CONDITION" VARCHAR2(254),
  "VALID_DATE"          CHAR(10),
  "INVALID_DATE"        CHAR(10),
  "LAST_MODIFY_DATE"    CHAR(10)
)
;
COMMENT ON TABLE PLUGIN_WT_CONDITION
  IS '02.等待条件表';
COMMENT ON COLUMN PLUGIN_WT_CONDITION."PLUGIN_CONF_ID"
  IS '配置标识符';
COMMENT ON COLUMN PLUGIN_WT_CONDITION."CONF_SORT"
  IS '配置顺序';
COMMENT ON COLUMN PLUGIN_WT_CONDITION."CHECK_ITEM_NAME"
  IS '检查项名称';
COMMENT ON COLUMN PLUGIN_WT_CONDITION."CHECK_ITEM_SQL"
  IS '检查项SQL';
COMMENT ON COLUMN PLUGIN_WT_CONDITION."CHECK_SUC_CONDITION"
  IS '检查成功条件';
COMMENT ON COLUMN PLUGIN_WT_CONDITION."VALID_DATE"
  IS '生效日期';
COMMENT ON COLUMN PLUGIN_WT_CONDITION."INVALID_DATE"
  IS '失效日期';
COMMENT ON COLUMN PLUGIN_WT_CONDITION."LAST_MODIFY_DATE"
  IS '最后更新日期';
ALTER TABLE PLUGIN_WT_CONDITION
  ADD PRIMARY KEY (PLUGIN_CONF_ID, CONF_SORT);

CREATE TABLE PLUGIN_WT_CONF
(
  "PLUGIN_CONF_ID" VARCHAR2(24) NOT NULL,
  "CHECK_INTEVAL"  NUMBER(11),
  "MAX_WAIT_TIME"  NUMBER(11),
  "WAIT_DESC"      VARCHAR2(80)
)
;
COMMENT ON TABLE PLUGIN_WT_CONF
  IS '01.等待指定条件配置表';
COMMENT ON COLUMN PLUGIN_WT_CONF."PLUGIN_CONF_ID"
  IS '配置标识符';
COMMENT ON COLUMN PLUGIN_WT_CONF."CHECK_INTEVAL"
  IS '等待间隔';
COMMENT ON COLUMN PLUGIN_WT_CONF."MAX_WAIT_TIME"
  IS '最长等待时间';
COMMENT ON COLUMN PLUGIN_WT_CONF."WAIT_DESC"
  IS '等待描述';
ALTER TABLE PLUGIN_WT_CONF
  ADD PRIMARY KEY (PLUGIN_CONF_ID);

CREATE TABLE PUB_SYS_INFO
(
  "SYS_ID"        VARCHAR2(32) NOT NULL,
  "SYS_NAME"      VARCHAR2(100),
  "HEADOFFICE"    VARCHAR2(20),
  "PROGRESS"      CHAR(2),
  "OPENDAY"       VARCHAR2(10),
  "LAST_OPENDAY"  VARCHAR2(10),
  "EFFECTIVEDAYS" NUMBER,
  "SYS_STATUS"    VARCHAR2(2),
  "LOGINMODE"     CHAR(1),
  "SLMODE"        CHAR(1)
)
;
COMMENT ON TABLE PUB_SYS_INFO
  IS '系统营业日期';
COMMENT ON COLUMN PUB_SYS_INFO."SYS_ID"
  IS '系统编号';
COMMENT ON COLUMN PUB_SYS_INFO."SYS_NAME"
  IS '系统名称';
COMMENT ON COLUMN PUB_SYS_INFO."HEADOFFICE"
  IS '未知';
COMMENT ON COLUMN PUB_SYS_INFO."PROGRESS"
  IS '未知';
COMMENT ON COLUMN PUB_SYS_INFO."OPENDAY"
  IS '营业日期';
COMMENT ON COLUMN PUB_SYS_INFO."LAST_OPENDAY"
  IS '上一营业日期';
COMMENT ON COLUMN PUB_SYS_INFO."EFFECTIVEDAYS"
  IS '未知';
COMMENT ON COLUMN PUB_SYS_INFO."SYS_STATUS"
  IS '系统状态';
COMMENT ON COLUMN PUB_SYS_INFO."LOGINMODE"
  IS '未知';
COMMENT ON COLUMN PUB_SYS_INFO."SLMODE"
  IS '未知';
ALTER TABLE PUB_SYS_INFO
  ADD PRIMARY KEY (SYS_ID);

CREATE TABLE S_AGENT_INFO
(
  "AGENT_ID"    VARCHAR2(32) NOT NULL,
  "AGENT_NAME"  VARCHAR2(80),
  "AGENT_STATE" CHAR(1),
  "AGENT_URL"   VARCHAR2(128),
  "START_TIME"  VARCHAR2(24),
  "STOP_TIME"   VARCHAR2(24)
)
;
COMMENT ON TABLE S_AGENT_INFO
  IS '代理节点信息';
COMMENT ON COLUMN S_AGENT_INFO."AGENT_ID"
  IS '代理节点标识';
COMMENT ON COLUMN S_AGENT_INFO."AGENT_NAME"
  IS '代理节点名称';
COMMENT ON COLUMN S_AGENT_INFO."AGENT_STATE"
  IS '代理节点状态';
COMMENT ON COLUMN S_AGENT_INFO."AGENT_URL"
  IS '代理节点地址';
COMMENT ON COLUMN S_AGENT_INFO."START_TIME"
  IS '启动时间';
COMMENT ON COLUMN S_AGENT_INFO."STOP_TIME"
  IS '停止时间';
ALTER TABLE S_AGENT_INFO
  ADD PRIMARY KEY (AGENT_ID);

CREATE TABLE S_AUTOCODE
(
  "ATYPE"      VARCHAR2(20),
  "OWNER"      VARCHAR2(20),
  "INITCYCLE"  CHAR(1),
  "CUR_SERNUM" VARCHAR2(50),
  "ZERO_FLG"   CHAR(1),
  "CUR_DATE"   VARCHAR2(10)
)
;
COMMENT ON TABLE S_AUTOCODE
  IS '自动序号';
COMMENT ON COLUMN S_AUTOCODE."ATYPE"
  IS '类型';
COMMENT ON COLUMN S_AUTOCODE."OWNER"
  IS '拥有者';
COMMENT ON COLUMN S_AUTOCODE."INITCYCLE"
  IS '未知';
COMMENT ON COLUMN S_AUTOCODE."CUR_SERNUM"
  IS '当前序号值';
COMMENT ON COLUMN S_AUTOCODE."ZERO_FLG"
  IS '未知';
COMMENT ON COLUMN S_AUTOCODE."CUR_DATE"
  IS '当前日期';

CREATE TABLE S_DEPTUSER
(
  "ORGANNO" VARCHAR2(16) NOT NULL,
  "DEPNO"   VARCHAR2(16),
  "ACTORNO" VARCHAR2(8) NOT NULL,
  "STATE"   NUMBER,
  "ORGID"   VARCHAR2(16)
)
;
COMMENT ON TABLE S_DEPTUSER
  IS '用户部门关系表';
COMMENT ON COLUMN S_DEPTUSER."ORGANNO"
  IS '机构码';
COMMENT ON COLUMN S_DEPTUSER."DEPNO"
  IS '部门码';
COMMENT ON COLUMN S_DEPTUSER."ACTORNO"
  IS '用户码';
COMMENT ON COLUMN S_DEPTUSER."STATE"
  IS '状态';
COMMENT ON COLUMN S_DEPTUSER."ORGID"
  IS '组织号';
ALTER TABLE S_DEPTUSER
  ADD PRIMARY KEY (ORGANNO, ACTORNO);

CREATE TABLE S_INST_LICENSE
(
  "HOST_NAME"       VARCHAR2(24),
  "WEB_PORT"        VARCHAR2(5),
  "SYS_INST_ID"     VARCHAR2(48) NOT NULL,
  "SYS_CODE"        VARCHAR2(24),
  "SYS_NAME"        VARCHAR2(80),
  "AUTH_TARGET"     VARCHAR2(80),
  "AUTH_BEGIN_DATE" CHAR(10),
  "AUTH_END_DATE"   CHAR(10),
  "REMARK"          VARCHAR2(254)
)
;
COMMENT ON TABLE S_INST_LICENSE
  IS '01.系统注册授权信息';
COMMENT ON COLUMN S_INST_LICENSE."HOST_NAME"
  IS '主机名/IP地址';
COMMENT ON COLUMN S_INST_LICENSE."WEB_PORT"
  IS 'WEB端口';
COMMENT ON COLUMN S_INST_LICENSE."SYS_INST_ID"
  IS '系统实例标识';
COMMENT ON COLUMN S_INST_LICENSE."SYS_CODE"
  IS '系统代码';
COMMENT ON COLUMN S_INST_LICENSE."SYS_NAME"
  IS '系统名称';
COMMENT ON COLUMN S_INST_LICENSE."AUTH_TARGET"
  IS '授权目标';
COMMENT ON COLUMN S_INST_LICENSE."AUTH_BEGIN_DATE"
  IS '授权起始日期';
COMMENT ON COLUMN S_INST_LICENSE."AUTH_END_DATE"
  IS '授权截止日期';
COMMENT ON COLUMN S_INST_LICENSE."REMARK"
  IS '备注';
ALTER TABLE S_INST_LICENSE
  ADD PRIMARY KEY (SYS_INST_ID);

CREATE TABLE S_INST_SRVS_CONF
(
  "SRVS_INST_ID"     VARCHAR2(48) NOT NULL,
  "SRVS_CODE"        VARCHAR2(16),
  "SYS_INST_ID"      VARCHAR2(48),
  "IS_ALLOW_SERVICE" CHAR(1),
  "RSV_FLAG"         CHAR(1)
)
;
COMMENT ON TABLE S_INST_SRVS_CONF
  IS '02.服务实例配置信息';
COMMENT ON COLUMN S_INST_SRVS_CONF."SRVS_INST_ID"
  IS '服务组件实例标识';
COMMENT ON COLUMN S_INST_SRVS_CONF."SRVS_CODE"
  IS '服务组件代码';
COMMENT ON COLUMN S_INST_SRVS_CONF."SYS_INST_ID"
  IS '系统实例标识';
COMMENT ON COLUMN S_INST_SRVS_CONF."IS_ALLOW_SERVICE"
  IS '是否允许运行';
COMMENT ON COLUMN S_INST_SRVS_CONF."RSV_FLAG"
  IS '保留字段(标志)';
ALTER TABLE S_INST_SRVS_CONF
  ADD PRIMARY KEY (SRVS_INST_ID);

CREATE TABLE S_ORG
(
  "ORGANNO"            VARCHAR2(20),
  "SUPORGANNO"         VARCHAR2(20),
  "LOCATE"             VARCHAR2(100),
  "ORGANNAME"          VARCHAR2(40),
  "ORGANSHORTFORM"     VARCHAR2(40),
  "ENNAME"             VARCHAR2(40),
  "ORDERNO"            NUMBER,
  "DISTNO"             VARCHAR2(12),
  "LAUNCHDATE"         VARCHAR2(10),
  "ORGANLEVEL"         NUMBER,
  "FINCODE"            VARCHAR2(21),
  "STATE"              NUMBER,
  "ORGANCHIEF"         VARCHAR2(32),
  "TELNUM"             VARCHAR2(20),
  "ADDRESS"            VARCHAR2(200),
  "POSTCODE"           VARCHAR2(10),
  "CONTROL"            VARCHAR2(10),
  "ARTI_ORGANNO"       VARCHAR2(20),
  "DISTNAME"           VARCHAR2(100),
  "AREA_DEV_CATE_TYPE" VARCHAR2(1),
  "IS_MARKETING"       VARCHAR2(1),
  "BUSIORGANNO"        VARCHAR2(20)
)
;
COMMENT ON TABLE S_ORG
  IS '机构管理';
COMMENT ON COLUMN S_ORG."ORGANNO"
  IS '机构码';
COMMENT ON COLUMN S_ORG."SUPORGANNO"
  IS '上级机构码';
COMMENT ON COLUMN S_ORG."LOCATE"
  IS '所属地区';
COMMENT ON COLUMN S_ORG."ORGANNAME"
  IS '机构名称';
COMMENT ON COLUMN S_ORG."ORGANSHORTFORM"
  IS '机构简称';
COMMENT ON COLUMN S_ORG."ENNAME"
  IS '选项值';
COMMENT ON COLUMN S_ORG."ORDERNO"
  IS '排序字段';
COMMENT ON COLUMN S_ORG."DISTNO"
  IS '地区编号';
COMMENT ON COLUMN S_ORG."LAUNCHDATE"
  IS '开办日期';
COMMENT ON COLUMN S_ORG."ORGANLEVEL"
  IS '机构级别';
COMMENT ON COLUMN S_ORG."FINCODE"
  IS '金融代码';
COMMENT ON COLUMN S_ORG."STATE"
  IS '状态';
COMMENT ON COLUMN S_ORG."ORGANCHIEF"
  IS '机构负责人';
COMMENT ON COLUMN S_ORG."TELNUM"
  IS '联系电话';
COMMENT ON COLUMN S_ORG."ADDRESS"
  IS '地址';
COMMENT ON COLUMN S_ORG."POSTCODE"
  IS '邮编';
COMMENT ON COLUMN S_ORG."CONTROL"
  IS '控制字';
COMMENT ON COLUMN S_ORG."ARTI_ORGANNO"
  IS '所属法人机构码';
COMMENT ON COLUMN S_ORG."DISTNAME"
  IS '地区名称';
COMMENT ON COLUMN S_ORG."AREA_DEV_CATE_TYPE"
  IS '地区发展分类';
COMMENT ON COLUMN S_ORG."IS_MARKETING"
  IS '是否营销中心';
COMMENT ON COLUMN S_ORG."BUSIORGANNO"
  IS '业务机构编号';

CREATE TABLE S_PARAM_INFO
(
  "PARAM_CODE"  VARCHAR2(32) NOT NULL,
  "PARAM_NAME"  VARCHAR2(64),
  "PARAM_VALUE" VARCHAR2(512),
  "PARAM_SCOPE" CHAR(1),
  "SUBS_CODE"   VARCHAR2(16),
  "PLUGIN_ID"   NUMBER(11),
  "REMARK"      VARCHAR2(254)
)
;
COMMENT ON TABLE S_PARAM_INFO
  IS '01.平台参数信息表';
COMMENT ON COLUMN S_PARAM_INFO."PARAM_CODE"
  IS '参数代码';
COMMENT ON COLUMN S_PARAM_INFO."PARAM_NAME"
  IS '参数名称';
COMMENT ON COLUMN S_PARAM_INFO."PARAM_VALUE"
  IS '参数值';
COMMENT ON COLUMN S_PARAM_INFO."PARAM_SCOPE"
  IS '参数使用范围';
COMMENT ON COLUMN S_PARAM_INFO."SUBS_CODE"
  IS '子系统代码';
COMMENT ON COLUMN S_PARAM_INFO."PLUGIN_ID"
  IS '应用插件ID';
COMMENT ON COLUMN S_PARAM_INFO."REMARK"
  IS '备注';
ALTER TABLE S_PARAM_INFO
  ADD PRIMARY KEY (PARAM_CODE);

CREATE TABLE S_RESOURCE
(
  "RESOURCEID" VARCHAR2(32) NOT NULL,
  "CNNAME"     VARCHAR2(50),
  "SYSTEMPK"   VARCHAR2(20),
  "URL"        VARCHAR2(254),
  "PARENTID"   VARCHAR2(50),
  "TABLENAME"  VARCHAR2(50),
  "PROCID"     VARCHAR2(100),
  "ORDERID"    VARCHAR2(20),
  "MEMO"       VARCHAR2(50),
  "ICON"       VARCHAR2(100),
  "ORGID"      VARCHAR2(16)
)
;
COMMENT ON TABLE S_RESOURCE
  IS '资源定义';
COMMENT ON COLUMN S_RESOURCE."RESOURCEID"
  IS '资源ID';
COMMENT ON COLUMN S_RESOURCE."CNNAME"
  IS '选项名称';
COMMENT ON COLUMN S_RESOURCE."SYSTEMPK"
  IS '所属子系统';
COMMENT ON COLUMN S_RESOURCE."URL"
  IS '资源URL';
COMMENT ON COLUMN S_RESOURCE."PARENTID"
  IS '上级资源ID';
COMMENT ON COLUMN S_RESOURCE."TABLENAME"
  IS '表名';
COMMENT ON COLUMN S_RESOURCE."PROCID"
  IS '流程模板';
COMMENT ON COLUMN S_RESOURCE."ORDERID"
  IS '序号';
COMMENT ON COLUMN S_RESOURCE."MEMO"
  IS '备注';
COMMENT ON COLUMN S_RESOURCE."ICON"
  IS '资源图标';
COMMENT ON COLUMN S_RESOURCE."ORGID"
  IS '组织号';
ALTER TABLE S_RESOURCE
  ADD PRIMARY KEY (RESOURCEID);

CREATE TABLE S_RESOURCEACTION
(
  "RESOURCEID" VARCHAR2(32) NOT NULL,
  "ACTID"      VARCHAR2(32) NOT NULL,
  "DESCR"      VARCHAR2(50),
  "FLAG"       VARCHAR2(50),
  "CONFIRMMSG" VARCHAR2(100),
  "ORGID"      VARCHAR2(16)
)
;
COMMENT ON TABLE S_RESOURCEACTION
  IS '资源操作';
COMMENT ON COLUMN S_RESOURCEACTION."RESOURCEID"
  IS '资源ID';
COMMENT ON COLUMN S_RESOURCEACTION."ACTID"
  IS '操作ID';
COMMENT ON COLUMN S_RESOURCEACTION."DESCR"
  IS '描述';
COMMENT ON COLUMN S_RESOURCEACTION."FLAG"
  IS '标志';
COMMENT ON COLUMN S_RESOURCEACTION."CONFIRMMSG"
  IS '提示确认信息';
COMMENT ON COLUMN S_RESOURCEACTION."ORGID"
  IS '组织号';
ALTER TABLE S_RESOURCEACTION
  ADD PRIMARY KEY (RESOURCEID, ACTID);

CREATE TABLE S_ROLE
(
  "ROLENO"   VARCHAR2(4) NOT NULL,
  "ROLENAME" VARCHAR2(40),
  "ORDERNO"  NUMBER,
  "TYPE"     NUMBER,
  "MEMO"     VARCHAR2(60),
  "ORGID"    VARCHAR2(16)
)
;
COMMENT ON TABLE S_ROLE
  IS '角色控制配置表';
COMMENT ON COLUMN S_ROLE."ROLENO"
  IS '角色码';
COMMENT ON COLUMN S_ROLE."ROLENAME"
  IS '角色名称';
COMMENT ON COLUMN S_ROLE."ORDERNO"
  IS '排序字段';
COMMENT ON COLUMN S_ROLE."TYPE"
  IS '类型';
COMMENT ON COLUMN S_ROLE."MEMO"
  IS '备注';
COMMENT ON COLUMN S_ROLE."ORGID"
  IS '组织号';
ALTER TABLE S_ROLE
  ADD PRIMARY KEY (ROLENO);

CREATE TABLE S_ROLERIGHT
(
  "ROLENO"     CHAR(4),
  "RESOURCEID" VARCHAR2(32),
  "ACTID"      VARCHAR2(32),
  "STATE"      NUMBER,
  "ORGID"      VARCHAR2(16)
)
;
COMMENT ON TABLE S_ROLERIGHT
  IS '资源权限';
COMMENT ON COLUMN S_ROLERIGHT."ROLENO"
  IS '角色编号';
COMMENT ON COLUMN S_ROLERIGHT."RESOURCEID"
  IS '资源ID';
COMMENT ON COLUMN S_ROLERIGHT."ACTID"
  IS '操作ID';
COMMENT ON COLUMN S_ROLERIGHT."STATE"
  IS '状态';
COMMENT ON COLUMN S_ROLERIGHT."ORGID"
  IS '组织号';

CREATE TABLE S_ROLEUSER
(
  "ROLENO"  CHAR(4) NOT NULL,
  "ACTORNO" VARCHAR2(8) NOT NULL,
  "STATE"   NUMBER,
  "ORGID"   VARCHAR2(16)
)
;
COMMENT ON TABLE S_ROLEUSER
  IS '用户角色关系表';
COMMENT ON COLUMN S_ROLEUSER."ROLENO"
  IS '角色码';
COMMENT ON COLUMN S_ROLEUSER."ACTORNO"
  IS '用户码';
COMMENT ON COLUMN S_ROLEUSER."STATE"
  IS '状态';
COMMENT ON COLUMN S_ROLEUSER."ORGID"
  IS '组织号';
ALTER TABLE S_ROLEUSER
  ADD PRIMARY KEY (ROLENO, ACTORNO);

CREATE TABLE S_SRVS_ADMIN_LOG
(
  "SRVS_INST_ID"       VARCHAR2(48),
  "SRVS_INST_ACTION"   CHAR(2),
  "ACTION_TIME"        VARCHAR2(24),
  "ACTION_RESULT"      CHAR(1),
  "ACTION_DETAIL_INFO" NCLOB,
  "SERIAL_NO"          VARCHAR2(32) NOT NULL
)
;
COMMENT ON TABLE S_SRVS_ADMIN_LOG
  IS '02.服务管理日志';
COMMENT ON COLUMN S_SRVS_ADMIN_LOG."SRVS_INST_ID"
  IS '服务组件实例标识';
COMMENT ON COLUMN S_SRVS_ADMIN_LOG."SRVS_INST_ACTION"
  IS '实例操作类型';
COMMENT ON COLUMN S_SRVS_ADMIN_LOG."ACTION_TIME"
  IS '操作时间';
COMMENT ON COLUMN S_SRVS_ADMIN_LOG."ACTION_RESULT"
  IS '操作结果';
COMMENT ON COLUMN S_SRVS_ADMIN_LOG."ACTION_DETAIL_INFO"
  IS '操作详情';
COMMENT ON COLUMN S_SRVS_ADMIN_LOG."SERIAL_NO"
  IS '流水号';
ALTER TABLE S_SRVS_ADMIN_LOG
  ADD PRIMARY KEY (SERIAL_NO);

CREATE TABLE S_SRVS_CALLED_LOG
(
  "CLIENT_IP"        VARCHAR2(24),
  "CLIENT_USERID"    VARCHAR2(20),
  "SRVS_INST_ID"     VARCHAR2(48),
  "SRVS_LOG_TYPE"    VARCHAR2(16),
  "SRVS_BUSI_CODE"   VARCHAR2(16),
  "COST_TIME"        NUMBER,
  "START_TIME"       VARCHAR2(24),
  "STOP_TIME"        VARCHAR2(24),
  "IN_BUFFER"        NCLOB,
  "OUT_BUFFER"       NCLOB,
  "SRVS_BUSI_RESULT" CHAR(1),
  "SERIAL_NO"        VARCHAR2(32) NOT NULL
)
;
COMMENT ON TABLE S_SRVS_CALLED_LOG
  IS '03.服务调用日志';
COMMENT ON COLUMN S_SRVS_CALLED_LOG."CLIENT_IP"
  IS '客户端IP地址';
COMMENT ON COLUMN S_SRVS_CALLED_LOG."CLIENT_USERID"
  IS '客户端用户';
COMMENT ON COLUMN S_SRVS_CALLED_LOG."SRVS_INST_ID"
  IS '服务组件实例标识';
COMMENT ON COLUMN S_SRVS_CALLED_LOG."SRVS_LOG_TYPE"
  IS '服务日志类型';
COMMENT ON COLUMN S_SRVS_CALLED_LOG."SRVS_BUSI_CODE"
  IS '交易代码';
COMMENT ON COLUMN S_SRVS_CALLED_LOG."COST_TIME"
  IS '执行时长（秒）';
COMMENT ON COLUMN S_SRVS_CALLED_LOG."START_TIME"
  IS '启动时间';
COMMENT ON COLUMN S_SRVS_CALLED_LOG."STOP_TIME"
  IS '停止时间';
COMMENT ON COLUMN S_SRVS_CALLED_LOG."IN_BUFFER"
  IS '输入数据';
COMMENT ON COLUMN S_SRVS_CALLED_LOG."OUT_BUFFER"
  IS '输出数据';
COMMENT ON COLUMN S_SRVS_CALLED_LOG."SRVS_BUSI_RESULT"
  IS '交易结果';
COMMENT ON COLUMN S_SRVS_CALLED_LOG."SERIAL_NO"
  IS '流水号';
ALTER TABLE S_SRVS_CALLED_LOG
  ADD PRIMARY KEY (SERIAL_NO);

CREATE TABLE S_SRVS_CRON_CONF
(
  "JOB_CODE"        VARCHAR2(40) NOT NULL,
  "JOB_DESC"        VARCHAR2(80),
  "JOB_CLASS_TYPE"  VARCHAR2(16),
  "JOB_CLASS"       VARCHAR2(128),
  "JOB_METHOD"      VARCHAR2(60),
  "SERVICE_VERSION" VARCHAR2(8),
  "SERVICE_GROUP"   VARCHAR2(16),
  "SERVICE_TIMEOUT" NUMBER(11),
  "CRON_EXPRESSION" VARCHAR2(32),
  "AGAIN_TIME"      NUMBER(11),
  "RETRY_SECOND"    NUMBER(11),
  "AGENT_ID"        VARCHAR2(32),
  "REMARK"          VARCHAR2(254)
)
;
COMMENT ON TABLE S_SRVS_CRON_CONF
  IS '定时调度配置';
COMMENT ON COLUMN S_SRVS_CRON_CONF."JOB_CODE"
  IS '定时作业编号';
COMMENT ON COLUMN S_SRVS_CRON_CONF."JOB_DESC"
  IS '定时作业描述';
COMMENT ON COLUMN S_SRVS_CRON_CONF."JOB_CLASS_TYPE"
  IS '作业类类型';
COMMENT ON COLUMN S_SRVS_CRON_CONF."JOB_CLASS"
  IS '作业实现类';
COMMENT ON COLUMN S_SRVS_CRON_CONF."JOB_METHOD"
  IS '作业类方法';
COMMENT ON COLUMN S_SRVS_CRON_CONF.SERVICE_VERSION
  IS '服务版本';
COMMENT ON COLUMN S_SRVS_CRON_CONF.SERVICE_GROUP
  IS '服务分组';
COMMENT ON COLUMN S_SRVS_CRON_CONF.SERVICE_TIMEOUT
  is '服务超时时间';
COMMENT ON COLUMN S_SRVS_CRON_CONF."CRON_EXPRESSION"
  IS 'CRON表达式';
COMMENT ON COLUMN S_SRVS_CRON_CONF."AGAIN_TIME"
  IS '失败重试次数';
COMMENT ON COLUMN S_SRVS_CRON_CONF."RETRY_SECOND"
  IS '重试间隔秒数';
COMMENT ON COLUMN S_SRVS_CRON_CONF."AGENT_ID"
  IS '代理节点标识';
COMMENT ON COLUMN S_SRVS_CRON_CONF."REMARK"
  IS '备注';
ALTER TABLE S_SRVS_CRON_CONF
  ADD PRIMARY KEY (JOB_CODE);

CREATE TABLE S_SRVS_CRON_HIS
(
  "RECORD_ID"   CHAR(32) NOT NULL,
  "JOB_CODE"    VARCHAR2(40),
  "JOB_DESC"    VARCHAR2(80),
  "STATE"       NUMBER(11),
  "START_TIME"  VARCHAR2(24),
  "END_TIME"    VARCHAR2(24),
  "COST_TIME"   NUMBER,
  "AGENT_ID"    VARCHAR2(32),
  "RESULT_DESC" NCLOB
)
;
COMMENT ON TABLE S_SRVS_CRON_HIS
  IS '定时调度历史';
COMMENT ON COLUMN S_SRVS_CRON_HIS."RECORD_ID"
  IS '记录ID';
COMMENT ON COLUMN S_SRVS_CRON_HIS."JOB_CODE"
  IS '定时作业编号';
COMMENT ON COLUMN S_SRVS_CRON_HIS."JOB_DESC"
  IS '定时作业描述';
COMMENT ON COLUMN S_SRVS_CRON_HIS."STATE"
  IS '状态';
COMMENT ON COLUMN S_SRVS_CRON_HIS."START_TIME"
  IS '启动时间';
COMMENT ON COLUMN S_SRVS_CRON_HIS."END_TIME"
  IS '结束时间';
COMMENT ON COLUMN S_SRVS_CRON_HIS."COST_TIME"
  IS '耗时(秒)';
COMMENT ON COLUMN S_SRVS_CRON_HIS."AGENT_ID"
  IS '代理节点标识';
COMMENT ON COLUMN S_SRVS_CRON_HIS."RESULT_DESC"
  IS '结果描述';
ALTER TABLE S_SRVS_CRON_HIS
  ADD PRIMARY KEY (RECORD_ID);

CREATE TABLE S_SRVS_CRON_INST
(
  "JOB_CODE"    VARCHAR2(40) NOT NULL,
  "JOB_DESC"    VARCHAR2(80),
  "STATE"       NUMBER(11),
  "START_TIME"  VARCHAR2(24),
  "END_TIME"    VARCHAR2(24),
  "COST_TIME"   NUMBER,
  "AGENT_ID"    VARCHAR2(32),
  "RESULT_DESC" NCLOB
)
;
COMMENT ON TABLE S_SRVS_CRON_INST
  IS '定时调度实例';
COMMENT ON COLUMN S_SRVS_CRON_INST."JOB_CODE"
  IS '定时作业编号';
COMMENT ON COLUMN S_SRVS_CRON_INST."JOB_DESC"
  IS '定时作业描述';
COMMENT ON COLUMN S_SRVS_CRON_INST."STATE"
  IS '状态';
COMMENT ON COLUMN S_SRVS_CRON_INST."START_TIME"
  IS '启动时间';
COMMENT ON COLUMN S_SRVS_CRON_INST."END_TIME"
  IS '结束时间';
COMMENT ON COLUMN S_SRVS_CRON_INST."COST_TIME"
  IS '耗时(秒)';
COMMENT ON COLUMN S_SRVS_CRON_INST."AGENT_ID"
  IS '代理节点标识';
COMMENT ON COLUMN S_SRVS_CRON_INST."RESULT_DESC"
  IS '结果描述';
ALTER TABLE S_SRVS_CRON_INST
  ADD PRIMARY KEY (JOB_CODE);

CREATE TABLE S_SRVS_DEFINE
(
  "SRVS_CODE"         VARCHAR2(16) NOT NULL,
  "SRVS_NAME"         VARCHAR2(80),
  "SRVS_CLASS"        VARCHAR2(254),
  "SRVS_DESC"         VARCHAR2(254),
  "SRVS_TYPE"         CHAR(1),
  "IS_PRVD_CONF_PAGE" CHAR(1),
  "IS_PRVD_MGR_PAGE"  CHAR(1),
  "IS_PRVD_LOG"       CHAR(1),
  "IS_FLUX_CONTROL"   CHAR(1),
  "MAX_FLUX"          NUMBER(11)
)
;
COMMENT ON TABLE S_SRVS_DEFINE
  IS '01.服务组件信息';
COMMENT ON COLUMN S_SRVS_DEFINE."SRVS_CODE"
  IS '服务组件代码';
COMMENT ON COLUMN S_SRVS_DEFINE."SRVS_NAME"
  IS '服务组件名称';
COMMENT ON COLUMN S_SRVS_DEFINE."SRVS_CLASS"
  IS '服务实现类';
COMMENT ON COLUMN S_SRVS_DEFINE."SRVS_DESC"
  IS '服务描述';
COMMENT ON COLUMN S_SRVS_DEFINE."SRVS_TYPE"
  IS '服务组件类型';
COMMENT ON COLUMN S_SRVS_DEFINE."IS_PRVD_CONF_PAGE"
  IS '是否提供配置页面';
COMMENT ON COLUMN S_SRVS_DEFINE."IS_PRVD_MGR_PAGE"
  IS '是否提供管理页面';
COMMENT ON COLUMN S_SRVS_DEFINE."IS_PRVD_LOG"
  IS '是否提供服务日志';
COMMENT ON COLUMN S_SRVS_DEFINE."IS_FLUX_CONTROL"
  IS '是否支持流量控制';
COMMENT ON COLUMN S_SRVS_DEFINE."MAX_FLUX"
  IS '最大同时处理数';
ALTER TABLE S_SRVS_DEFINE
  ADD PRIMARY KEY (SRVS_CODE);

CREATE TABLE S_SUBS_DATASOURCE
(
  "SUBS_CODE"      VARCHAR2(16) NOT NULL,
  "SUBS_DS_CODE"   VARCHAR2(40) NOT NULL,
  "SUBS_DS_NAME"   VARCHAR2(80),
  "DS_CONN_STR"    VARCHAR2(128),
  "DS_USER_ID"     VARCHAR2(16),
  "DS_USER_PWD"    VARCHAR2(64),
  "DS_SCHEMA_NAME" VARCHAR2(16),
  "DS_DB_NAME"     VARCHAR2(32),
  "SUBS_DS_TYPE"   CHAR(2)
)
;
COMMENT ON TABLE S_SUBS_DATASOURCE
  IS '03.平台子系统数据源信息表';
COMMENT ON COLUMN S_SUBS_DATASOURCE."SUBS_CODE"
  IS '子系统代码';
COMMENT ON COLUMN S_SUBS_DATASOURCE."SUBS_DS_CODE"
  IS '子系统数据源代码';
COMMENT ON COLUMN S_SUBS_DATASOURCE."SUBS_DS_NAME"
  IS '子系统数据源名称';
COMMENT ON COLUMN S_SUBS_DATASOURCE."DS_CONN_STR"
  IS '数据源-连接字符串';
COMMENT ON COLUMN S_SUBS_DATASOURCE."DS_USER_ID"
  IS '数据源-用户名';
COMMENT ON COLUMN S_SUBS_DATASOURCE."DS_USER_PWD"
  IS '数据源-用户密码';
COMMENT ON COLUMN S_SUBS_DATASOURCE."DS_SCHEMA_NAME"
  IS '数据源-模式';
COMMENT ON COLUMN S_SUBS_DATASOURCE."DS_DB_NAME"
  IS '数据源-数据库名';
COMMENT ON COLUMN S_SUBS_DATASOURCE."SUBS_DS_TYPE"
  IS '子系统数据源类型';
ALTER TABLE S_SUBS_DATASOURCE
  ADD PRIMARY KEY (SUBS_CODE, SUBS_DS_CODE);

CREATE TABLE S_SUBS_INFO
(
  "SUBS_CODE"           VARCHAR2(16) NOT NULL,
  "SUBS_NAME"           VARCHAR2(80),
  "SUBS_DATA_DATE"      CHAR(10),
  "SUBS_LAST_DATA_DATE" CHAR(10),
  "SUBS_LOAD_DATE"      CHAR(10),
  "SUBS_BAT_DATE"       CHAR(10),
  "BATCH_ID_PREFIX"     VARCHAR2(16),
  "RSV_DATE"            CHAR(10),
  "RSV_STATE"           CHAR(2)
)
;
COMMENT ON TABLE S_SUBS_INFO
  IS '01.平台子系统基础信息表';
COMMENT ON COLUMN S_SUBS_INFO."SUBS_CODE"
  IS '子系统代码';
COMMENT ON COLUMN S_SUBS_INFO."SUBS_NAME"
  IS '子系统名称';
COMMENT ON COLUMN S_SUBS_INFO."SUBS_DATA_DATE"
  IS '子系统数据日期';
COMMENT ON COLUMN S_SUBS_INFO."SUBS_LAST_DATA_DATE"
  IS '子系统上一数据日期';
COMMENT ON COLUMN S_SUBS_INFO."SUBS_LOAD_DATE"
  IS '子系统装数完成日期';
COMMENT ON COLUMN S_SUBS_INFO."SUBS_BAT_DATE"
  IS '子系统批次完成日期';
COMMENT ON COLUMN S_SUBS_INFO."BATCH_ID_PREFIX"
  IS '批次编号前缀';
COMMENT ON COLUMN S_SUBS_INFO."RSV_DATE"
  IS '备用日期';
COMMENT ON COLUMN S_SUBS_INFO."RSV_STATE"
  IS '备用状态';
ALTER TABLE S_SUBS_INFO
  ADD PRIMARY KEY (SUBS_CODE);

CREATE TABLE S_SUBS_TABLES
(
  "SUBS_CODE"    VARCHAR2(16) NOT NULL,
  "TAB_NAME"     VARCHAR2(40),
  "REMARK"       VARCHAR2(254),
  "VALID_DATE"   CHAR(10),
  "INVALID_DATE" CHAR(10)
)
;
COMMENT ON TABLE S_SUBS_TABLES
  IS '02.平台子系统所需表信息';
COMMENT ON COLUMN S_SUBS_TABLES."SUBS_CODE"
  IS '子系统代码';
COMMENT ON COLUMN S_SUBS_TABLES."TAB_NAME"
  IS '表名称';
COMMENT ON COLUMN S_SUBS_TABLES."REMARK"
  IS '备注';
COMMENT ON COLUMN S_SUBS_TABLES."VALID_DATE"
  IS '生效日期';
COMMENT ON COLUMN S_SUBS_TABLES."INVALID_DATE"
  IS '失效日期';
ALTER TABLE S_SUBS_TABLES
  ADD PRIMARY KEY (SUBS_CODE);

CREATE TABLE S_USER
(
  "ACTORNO"          VARCHAR2(8) NOT NULL,
  "ENNAME"           VARCHAR2(32),
  "ACTORNAME"        VARCHAR2(20),
  "NICKNAME"         VARCHAR2(40),
  "STATE"            CHAR(1),
  "PASSWORD"         VARCHAR2(32),
  "STARTDATE"        CHAR(10),
  "PASSWVALDA"       CHAR(10),
  "FIREDATE"         CHAR(10),
  "BIRTHDAY"         CHAR(10),
  "TELNUM"           VARCHAR2(20),
  "IDCARDNO"         VARCHAR2(20),
  "ALLOWOPERSYS"     CHAR(20),
  "LASTLOGDAT"       CHAR(10),
  "CREATER"          VARCHAR2(40),
  "CREATTIME"        CHAR(10),
  "USERMAIL"         VARCHAR2(50),
  "WRONGPINNUM"      NUMBER,
  "ISADMIN"          CHAR(1),
  "MEMO"             VARCHAR2(200),
  "IPMASK"           VARCHAR2(40),
  "ORDERNO"          NUMBER,
  "QUESTION"         VARCHAR2(200),
  "ANSWER"           VARCHAR2(200),
  "ORGID"            VARCHAR2(16),
  "DEPNO"            VARCHAR2(16),
  "SESSION_ID"       VARCHAR2(40),
  "RANK"             CHAR(2),
  "PARENTACTORNO"    VARCHAR2(8),
  "DEVICE_NO"        VARCHAR2(18),
  "MENU_CONFIG"      BLOB,
  "IS_PRIORITY_SHOW" CHAR(1),
  "IF_TOGETHER_WF"   CHAR(1),
  "OP_MODEL"         CHAR(1),
  "MOB_NUM"          VARCHAR2(20)
)
;
COMMENT ON TABLE S_USER
  IS '用户管理';
COMMENT ON COLUMN S_USER."ACTORNO"
  IS '用户码';
COMMENT ON COLUMN S_USER."ENNAME"
  IS '选项值';
COMMENT ON COLUMN S_USER."ACTORNAME"
  IS '用户名称';
COMMENT ON COLUMN S_USER."NICKNAME"
  IS '昵称';
COMMENT ON COLUMN S_USER."STATE"
  IS '状态';
COMMENT ON COLUMN S_USER."PASSWORD"
  IS '密码';
COMMENT ON COLUMN S_USER."STARTDATE"
  IS '启用日期';
COMMENT ON COLUMN S_USER."PASSWVALDA"
  IS '密码';
COMMENT ON COLUMN S_USER."FIREDATE"
  IS '解雇日期';
COMMENT ON COLUMN S_USER."BIRTHDAY"
  IS '生日';
COMMENT ON COLUMN S_USER."TELNUM"
  IS '联系电话';
COMMENT ON COLUMN S_USER."IDCARDNO"
  IS '身份证号码';
COMMENT ON COLUMN S_USER."ALLOWOPERSYS"
  IS '允许操作的系统';
COMMENT ON COLUMN S_USER."LASTLOGDAT"
  IS '最后登陆日期';
COMMENT ON COLUMN S_USER."CREATER"
  IS '创建人';
COMMENT ON COLUMN S_USER."CREATTIME"
  IS '创建时间';
COMMENT ON COLUMN S_USER."USERMAIL"
  IS '邮箱';
COMMENT ON COLUMN S_USER."WRONGPINNUM"
  IS '密码输入错误次数';
COMMENT ON COLUMN S_USER."ISADMIN"
  IS '是否管理员';
COMMENT ON COLUMN S_USER."MEMO"
  IS '备注';
COMMENT ON COLUMN S_USER."IPMASK"
  IS '用户IP掩码';
COMMENT ON COLUMN S_USER."ORDERNO"
  IS '排序字段';
COMMENT ON COLUMN S_USER."QUESTION"
  IS '用户防伪问题';
COMMENT ON COLUMN S_USER."ANSWER"
  IS '用户防伪答案';
COMMENT ON COLUMN S_USER."ORGID"
  IS '组织号';
COMMENT ON COLUMN S_USER."DEPNO"
  IS '部门编号';
COMMENT ON COLUMN S_USER."SESSION_ID"
  IS '当前登录会话ID';
COMMENT ON COLUMN S_USER."RANK"
  IS '职级';
COMMENT ON COLUMN S_USER."PARENTACTORNO"
  IS '主账号用户码';
COMMENT ON COLUMN S_USER."DEVICE_NO"
  IS '未知';
COMMENT ON COLUMN S_USER."MENU_CONFIG"
  IS '未知';
COMMENT ON COLUMN S_USER."IS_PRIORITY_SHOW"
  IS '是否优先显示';
COMMENT ON COLUMN S_USER."IF_TOGETHER_WF"
  IS '是否合并待办';
COMMENT ON COLUMN S_USER."OP_MODEL"
  IS '操作模式';
COMMENT ON COLUMN S_USER."MOB_NUM"
  IS '手机号码';
ALTER TABLE S_USER
  ADD PRIMARY KEY (ACTORNO);